### ISSUE TITLE
你好 怎么播放本地下载好的m3u8文件呢？

### ISSUE THREAD

**Issue by jj89757hhb** [luoxubin/XB2#1]
你好 怎么播放本地下载好的m3u8文件呢？

**Comment by songbaoqiang** [comment]
本地起一个Local http server，模仿web server 模式播放。。。

**Comment by jj89757hhb** [comment]
哦  您有有效的m3u8地址测试吗

**Comment by songbaoqiang** [comment]
搜索一下很多。

**Comment by jj89757hhb** [comment]
感觉没有呢

**Comment by songbaoqiang** [comment]
不要用百度 用谷歌

On Mon, Jan 25, 2016 at 1:14 PM, testPublicProfile <notifications@github.com

**Comment by jj89757hhb** [comment]
ios端到底能播放本地的 m3u8文件吗？

**Comment by songbaoqiang** [comment]
可以。

**Comment by luoxubin** [comment]
如果 @songbaoqiang ，需要搭建本地的httpserver就可以。关闭issue

**Comment by jj89757hhb** [comment]
已解决 ，谢谢大家回答
